### ISSUE TITLE
Program wont start, cites no attribute logfile

### ISSUE THREAD

**Issue by BurninTurtles** [fofix/fretwork#30]
here is the crashlog:
```
Traceback (most recent call last):
  File "FoFiX.py", line 128, in <module>
    log.setLogfile(logFile)
AttributeError: 'module' object has no attribute 'setLogfile'

[1]  + 8953 exit 1     python FoFiX.py
```
end log. 

I recently git pulled to the latest git, did the usual "python setup.py build_ext --inplace --force", downloaded the latest fretwork. I had always believed this to be the standard setup. I am pretty sure i have all the required deb packages.

**Comment by Linkid** [comment]
Hi.

You're using the wrong version of fretwork : `setLogfile` was removed in 0.3.0 and FoFiX is still using the 0.2.0 as stated in the [requirements](https://github.com/fofix/fofix/blob/2ca8e2bb3dc540f994a6086fad1f888007a74053/requirements.txt).
(And I'm currently updating the fretwork version in FoFiX : https://github.com/fofix/fofix/pull/139.)

**Comment by BurninTurtles** [comment]
thanks for the speedy response :) I will wait another hour or so, redownload fretwork, and try again.
EDIT: i just reread that (long night of no sleep), ill do just what you said lol
