### ISSUE TITLE
Porting code to python 3

### ISSUE THREAD

**Issue by Linkid** [fofix/fretwork#57]
Porting the code to python 3 should be a good thing as python 2 will not be maintained past 2020 (https://pythonclock.org). Here are some links to help porting it:
- http://python3porting.com
- https://docs.python.org/3/howto/pyporting.html.

The goal of this issue is to sum up the work the code needs:
- [x] add / run tests (see #22, #23, #24)
- [x] port the code (see #14)
- [x] run tests again.

**Comment by es20490446e** [comment]
The disconnection of python versions between fofix and fretworks, plus the use of very old python2 packages, caused my distro to stop updating their fofix packages.

I have written a [new recipe](https://github.com/fofix/fretwork/files/6177292/fofix.zip), but it will only work when the game is ported.

**Comment by Linkid** [comment]
Hi @es20490446e !

Which distribution are you talking about ? I think debian stopped packaging fofix v3 due to the python version.

About your recipe, I encourage you to make some PR to our projects (or to the distribution you are talking about), to be able to validate them ;). It is better than a zip file.

Thanks for you future contributions.

**Comment by es20490446e** [comment]
My distro is Manjaro.

The zip is for my future self 😛

**Comment by Linkid** [comment]
Done
